### ISSUE TITLE
Problems when I train with two gpus

### ISSUE THREAD

**Issue by Xiejiahao233** [Jiahao-UTS/DSLPT#2]
Hello，Thank you for the great work. When I use two GPUs for training, I encountered the following problems during backward: 
“RuntimeError: grad can be implicitly created only for scalar outputs”
Have you ever encountered this problem and how did you solve it?

**Comment by Jiahao-UTS** [comment]
The code is only tested on a single gpu since I do not have a server with multi-gpu. You can train the model on a single gpu.

**Comment by Xiejiahao233** [comment]
Thanks for your reply!
